// Order-preserving split of PROJECTS (max-lines); append new projects to entries-part-2.ts.
// Part 1 holds the flagship entries: the first VISIBLE_PROJECT_COUNT of these
// render as full cards, the remainder of the registry sits in the archive.
import type { Project } from './types';
import {
  GAMEZILLA_HREF,
  IMAGE_ALT,
  LAMDERA_HREF,
  externalLink,
  toYouTubeVideoUrl,
} from './shared';

export const PROJECT_ENTRIES_PART_1: readonly Project[] = [
  {
    id: 'triangulator',
    title: 'Triangulator',
    setting: 'work',
    deployment: { t: 'private' },
    code: { t: 'private' },
    description:
      'Enterprise platform that automates course transfer evaluation between universities. I was technical lead: credit equivalency is modelled as a graph in Neo4j alongside Postgres, served through a Python/Flask GraphQL API, and reviewed in a Nuxt admin where institutions assign, boost, and reject ranked equivalency suggestions with a reason attached.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/triangulator.optimized.webp'],
    galleryImageSrc: [
      toYouTubeVideoUrl({ youTubeVideoId: 'yQCrMBHQrDM', autoplay: true }),
      '/triangulator/assigned-reject-reason.optimized.webp',
      '/triangulator/course-search-details-2.optimized.webp',
      '/triangulator/course-search-loading.optimized.webp',
      '/triangulator/course-search.optimized.webp',
      '/triangulator/find-course.optimized.webp',
      '/triangulator/inst-admin-all-users.optimized.webp',
      '/triangulator/inst-admin-assign.optimized.webp',
      '/triangulator/inst-admin-boost-suggestions.optimized.webp',
      '/triangulator/inst-admin-dashboard.optimized.webp',
      '/triangulator/inst-admin-download.optimized.webp',
      '/triangulator/inst-admin-new-suggestions.optimized.webp',
      '/triangulator/inst-admin-public-profile.optimized.webp',
      '/triangulator/inst-admin-summary.optimized.webp',
      '/triangulator/inst-admin-upload-choice.optimized.webp',
      '/triangulator/inst-admin-upload-course.optimized.webp',
      '/triangulator/inst-public-profile.optimized.webp',
      '/triangulator/new-suggestions-assign.optimized.webp',
      '/triangulator/public-search-filter.optimized.webp',
      '/triangulator/search-results.optimized.webp',
      '/triangulator/suggestion-details-reject-reason.optimized.webp',
      '/triangulator/suggestion-details.optimized.webp',
      '/triangulator/tri-admin-dashboard.optimized.webp',
      '/triangulator/tri-admin-new-suggestions.optimized.webp',
      '/triangulator/tri-admin-suggestion-details.optimized.webp',
      '/triangulator/tri-admin-summary.optimized.webp',
    ],
    topics: [
      'typescript',
      'vue',
      'tailwind',
      'nuxt',
      'postgres',
      'python',
      'graphql',
      'aws',
      'graphene',
      'flask',
      'neo4j',
      's3',
    ],
  },
  {
    id: 'gamezilla',
    title: 'gamezilla.app',
    setting: 'side',
    deployment: { t: 'public', url: GAMEZILLA_HREF },
    code: { t: 'private' },
    description: `${externalLink(GAMEZILLA_HREF, 'gamezilla.app')} is a real-time multiplayer gaming platform built on a full-stack TypeScript implementation of the Elm architecture. Migrated off the ${externalLink(LAMDERA_HREF, 'Lamdera')} platform — reimplementing what Lamdera gave away for free (wire format, state persistence, client reconnect) over plain WebSockets, incrementally, without a flag day.`,
    imageAlt: IMAGE_ALT,
    imageSrc: [
      '/gamezilla-app-screenshot.optimized.webp',
      '/gamezilla.optimized.webp',
    ],
    galleryImageSrc: [
      '/gamezilla-app-screenshot.optimized.webp',
      toYouTubeVideoUrl({ youTubeVideoId: 'VSLpdPvHbD4', autoplay: true }),
      '/gamezilla.optimized.webp',
    ],
    topics: [
      'typescript',
      'react',
      'postgres',
      'tailwind',
      'websocket',
      'bun',
      'sqlite',
    ],
  },
  {
    id: 'geviti-app',
    title: 'Geviti',
    setting: 'work',
    deployment: { t: 'public', url: 'https://app.gogeviti.com/' },
    code: { t: 'private' },
    description:
      'Health and longevity platform combining bloodwork analysis, personalized supplement protocols, prescription therapies, and care team coordination. I ship member-facing features across web and React Native, on Postgres and AWS, in a domain where correctness and auditability outrank velocity.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/geviti-app-screenshot.optimized.webp'],
    galleryImageSrc: ['/geviti-app-screenshot.optimized.webp'],
    topics: ['typescript', 'react', 'postgres', 'bun', 'aws', 'react-native'],
  },
  {
    id: 'infra-control-plane',
    title: 'Infrastructure control plane',
    setting: 'side',
    deployment: { t: 'private' },
    code: {
      t: 'public',
      url: 'https://github.com/crvouga/workspace/tree/main/packages/infra',
    },
    description:
      'One <code>services.yaml</code> is the desired state for a personal production fleet — Railway services, Cloudflare DNS and redirects, Neon databases, R2 buckets, GitHub secrets, and tunnels. A reconcile loop plans every phase and applies it. Stateless drift is removed freely; stateful resources are never auto-deleted, only reported with the explicit destroy command to run by hand. CI gates on Vault readiness before it will deploy anything. This is the fleet this site is served from, alongside a self-hosted OpenBao secrets service and a Turborepo remote cache backed by Cloudflare R2.',
    imageAlt: IMAGE_ALT,
    imageSrc: [],
    galleryImageSrc: [],
    topics: ['typescript', 'bun', 'docker', 'postgres', 's3'],
  },
  {
    id: 'headless-combobox',
    title: 'headless-combobox',
    setting: 'side',
    deployment: {
      t: 'public',
      url: 'https://svelte-headlesscombobox.chrisvouga.dev',
    },
    code: { t: 'public', url: 'https://github.com/crvouga/headless-combobox' },
    description: `A production-ready, framework-agnostic, zero-dependency TypeScript combobox library. The widget is a state machine with no DOM of its own, so one core drives React, Svelte, or anything else while staying WCAG conformant. ${externalLink('https://headlesscombobox.chrisvouga.dev', 'Documentation site')}.`,
    imageAlt: IMAGE_ALT,
    imageSrc: ['/headless-combobox-screenshot.optimized.webp'],
    galleryImageSrc: ['/headless-combobox-screenshot.optimized.webp'],
    topics: ['typescript'],
  },
  {
    id: 'llm-proxy',
    title: 'LLM Proxy',
    setting: 'side',
    deployment: { t: 'public', url: 'https://llm-proxy.chrisvouga.dev' },
    code: { t: 'public', url: 'https://github.com/crvouga/llm-server' },
    description:
      'Self-hosted OpenAI-compatible HTTP proxy that routes requests to configurable upstream APIs, supports custom auth headers (API keys and bearer tokens), and logs traffic to Postgres for analysis, health checks, and cost visibility.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/llm-proxy-screenshot.optimized.webp'],
    galleryImageSrc: [
      '/llm-proxy-screenshot.optimized.webp',
      toYouTubeVideoUrl({
        youTubeVideoId: 'Zsrk8x2X2uc',
        autoplay: true,
        mute: true,
      }),
    ],
    topics: [
      'typescript',
      'react',
      'tailwind',
      'bun',
      'postgres',
      'docker',
      'nodejs',
    ],
  },
  {
    id: 'orchard',
    title: 'Orchard',
    setting: 'work',
    deployment: { t: 'public', url: 'https://asuorchard.asu.edu/' },
    code: { t: 'private' },
    description:
      "ASU platform that lets instructors build highly customizable assignments. I architected and implemented the LTI 1.3 integration with ASU's LMS — OIDC single sign-on, signed grade passback, key rotation, and the failure paths for when a grade does not post.",
    imageAlt: IMAGE_ALT,
    imageSrc: ['/orchard.optimized.webp'],
    galleryImageSrc: ['/orchard.optimized.webp'],
    topics: ['php', 'mysql', 'drupal', 'bootstrap', 'javascript'],
    resume: { include: false },
  },
  {
    id: 'study-hall',
    title: 'Study Hall',
    setting: 'work',
    deployment: { t: 'public', url: 'https://gostudyhall.com/' },
    code: { t: 'private' },
    description:
      'Education platform ASU runs in partnership with the Study Hall YouTube channel. I rebuilt payment processing — cutting payment failures and turning a fragile flow into one that could be reasoned about and changed safely.',
    imageAlt: IMAGE_ALT,
    imageSrc: [
      '/study-hall-screenshot.optimized.webp',
      '/studyhall.optimized.webp',
    ],
    galleryImageSrc: [
      '/study-hall-screenshot.optimized.webp',
      toYouTubeVideoUrl({
        youTubeVideoId: 'BC4K0u7Zm4k',
        autoplay: true,
        mute: true,
      }),
      '/studyhall/1.optimized.webp',
      '/studyhall/2.optimized.webp',
      '/studyhall/3.optimized.webp',
      '/studyhall/4.optimized.webp',
      '/studyhall/5.optimized.webp',
      '/studyhall/6.optimized.webp',
      '/studyhall/7.optimized.webp',
      '/studyhall/8.optimized.webp',
      '/studyhall/9.optimized.webp',
      '/studyhall/10.optimized.webp',
      '/studyhall/11.optimized.webp',
      '/studyhall/12.optimized.webp',
      '/studyhall/13.optimized.webp',
    ],
    topics: [
      'javascript',
      'vue',
      'nuxt',
      'bootstrap',
      'aws',
      'dynamodb',
      'salesforce',
      'express',
      'nodejs',
    ],
  },
];
