// Order-preserving split of PROJECTS (max-lines); append new projects to entries-part-2.ts.
import type { Project } from './types';
import {
  GAMEZILLA_HREF,
  IMAGE_ALT,
  LAMDERA_HREF,
  externalLink,
  toYouTubeVideoUrl,
} from './shared';

export const PROJECT_ENTRIES_PART_1: readonly Project[] = [
  {
    id: 'gamezilla',
    title: 'gamezilla.app',
    setting: 'side',
    deployment: { t: 'public', url: GAMEZILLA_HREF },
    code: { t: 'private' },
    description: `${externalLink(GAMEZILLA_HREF, 'gamezilla.app')} is a real-time multiplayer gaming platform built with a full-stack TypeScript implementation of the Elm architecture. Successfully migrated from the ${externalLink(LAMDERA_HREF, 'Lamdera')} platform, demonstrating expertise in complex system migrations and real-time application architecture.`,
    imageAlt: IMAGE_ALT,
    imageSrc: [
      '/gamezilla-app-screenshot.optimized.webp',
      '/gamezilla.optimized.webp',
    ],
    galleryImageSrc: [
      '/gamezilla-app-screenshot.png',
      toYouTubeVideoUrl({ youTubeVideoId: 'VSLpdPvHbD4', autoplay: true }),
      '/gamezilla.png',
    ],
    topics: [
      'typescript',
      'react',
      'postgres',
      'tailwind',
      'websocket',
      'bun',
      'sqlite',
    ],
  },
  {
    id: 'geviti-app',
    title: 'Geviti',
    setting: 'work',
    deployment: { t: 'public', url: 'https://app.gogeviti.com/' },
    code: { t: 'private' },
    description:
      'Building features for a comprehensive health and longevity platform that combines bloodwork analysis, personalized supplement protocols, prescription therapies, and care team coordination. Developing tools that help users track their health metrics and optimize their well-being through proactive, data-driven care.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/geviti-app-screenshot.optimized.webp'],
    galleryImageSrc: ['/geviti-app-screenshot.png'],
    topics: ['typescript', 'react', 'postgres', 'bun', 'aws', 'react-native'],
  },
  {
    id: 'triangulator',
    title: 'Triangulator',
    setting: 'work',
    deployment: { t: 'private' },
    code: { t: 'private' },
    description:
      'Enterprise platform that automates course transfer evaluation between universities, streamlining the complex process of determining credit equivalencies. Led development as the technical lead, architecting scalable solutions for handling large-scale academic data processing.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/triangulator.optimized.webp'],
    galleryImageSrc: [
      toYouTubeVideoUrl({ youTubeVideoId: 'yQCrMBHQrDM', autoplay: true }),
      '/triangulator/assigned-reject-reason.png',
      '/triangulator/course-search-details-2.png',
      '/triangulator/course-search-loading.png',
      '/triangulator/course-search.png',
      '/triangulator/find-course.png',
      '/triangulator/inst-admin-all-users.png',
      '/triangulator/inst-admin-assign.png',
      '/triangulator/inst-admin-boost-suggestions.png',
      '/triangulator/inst-admin-dashboard.png',
      '/triangulator/inst-admin-download.png',
      '/triangulator/inst-admin-new-suggestions.png',
      '/triangulator/inst-admin-public-profile.png',
      '/triangulator/inst-admin-summary.png',
      '/triangulator/inst-admin-upload-choice.png',
      '/triangulator/inst-admin-upload-course.png',
      '/triangulator/inst-public-profile.png',
      '/triangulator/new-suggestions-assign.png',
      '/triangulator/public-search-filter.png',
      '/triangulator/search-results.png',
      '/triangulator/suggestion-details-reject-reason.png',
      '/triangulator/suggestion-details.png',
      '/triangulator/tri-admin-dashboard.png',
      '/triangulator/tri-admin-new-suggestions.png',
      '/triangulator/tri-admin-suggestion-details.png',
      '/triangulator/tri-admin-summary.png',
    ],
    topics: [
      'typescript',
      'vue',
      'tailwind',
      'nuxt',
      'postgres',
      'python',
      'graphql',
      'aws',
      'graphene',
      'flask',
      'neo4j',
      's3',
    ],
  },
  {
    id: 'study-hall',
    title: 'Study Hall',
    setting: 'work',
    deployment: { t: 'public', url: 'https://gostudyhall.com/' },
    code: { t: 'private' },
    description:
      'Educational platform developed in partnership with the Study Hall YouTube channel and ASU. Refactored the payment processing system to enhance reliability, maintainability, and user experience, reducing payment failures and improving system stability.',
    imageAlt: IMAGE_ALT,
    imageSrc: [
      '/study-hall-screenshot.optimized.webp',
      '/studyhall.optimized.webp',
    ],
    galleryImageSrc: [
      '/study-hall-screenshot.png',
      toYouTubeVideoUrl({
        youTubeVideoId: 'BC4K0u7Zm4k',
        autoplay: true,
        mute: true,
      }),
      '/studyhall/1.png',
      '/studyhall/2.png',
      '/studyhall/3.png',
      '/studyhall/4.png',
      '/studyhall/5.png',
      '/studyhall/6.png',
      '/studyhall/7.png',
      '/studyhall/8.png',
      '/studyhall/9.png',
      '/studyhall/10.png',
      '/studyhall/11.png',
      '/studyhall/12.png',
      '/studyhall/13.png',
    ],
    topics: [
      'javascript',
      'vue',
      'nuxt',
      'bootstrap',
      'aws',
      'dynamodb',
      'salesforce',
      'express',
      'nodejs',
    ],
  },
  {
    id: 'asu-earned-admissions',
    title: 'ASU Earned Admissions',
    setting: 'work',
    deployment: { t: 'public', url: 'https://ea.asu.edu/' },
    code: { t: 'private' },
    description:
      "Educational platform enabling learners to earn college credits and qualify for admission to over 100 ASU degree programs. Refactored the main backend codebase for improved maintainability and scalability. Built Salesforce automation to sync data between Salesforce and ASU's Canvas LMS. Developed a new opt-in flow for the earned admissions program.",
    imageAlt: IMAGE_ALT,
    imageSrc: ['/asu-earned-admission-screenshot.optimized.webp'],
    galleryImageSrc: ['/asu-earned-admission-screenshot.png'],
    topics: [
      'salesforce',
      'nodejs',
      'typescript',
      'express',
      'dynamodb',
      'aws',
    ],
    resume: { include: false },
  },
  {
    id: 'normalizer-app',
    title: 'normalizer.app',
    setting: 'side',
    deployment: { t: 'not-deployed-anymore' },
    code: { t: 'public', url: 'https://github.com/crvouga/normalizer.app.git' },
    description:
      'A web application that automates data normalization workflows, transforming tabular data (Excel, CSV) between schemas without manual Excel manipulation or custom Python scripts. Streamlines data processing for teams handling diverse data formats.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/normalizer-app-screenshot.optimized.webp'],
    galleryImageSrc: [
      '/normalizer-app-screenshot.png',
      toYouTubeVideoUrl({
        youTubeVideoId: 'xUtdHEUeUzs',
        autoplay: true,
        mute: true,
      }),
    ],
    topics: [
      'typescript',
      'react',
      'tailwind',
      'bun',
      'postgres',
      's3',
      'trpc',
      'zod',
    ],
    resume: { priority: 100 },
  },
  {
    id: 'sun-devils',
    title: 'Sun devils',
    setting: 'work',
    deployment: { t: 'public', url: 'https://sundevils.com/' },
    code: { t: 'private' },
    description:
      'Official website for the ASU Sun Devils athletics program. Developed interactive React components including real-time game schedules and dynamic news feeds, enhancing fan engagement and information accessibility.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/sun-devils-screenshot.optimized.webp'],
    galleryImageSrc: [
      '/sun-devils-screenshot.png',
      '/sun-devils/2.png',
      '/sun-devils/3.png',
      '/sun-devils/4.png',
      '/sun-devils/5.png',
    ],
    topics: ['bootstrap', 'drupal', 'javascript', 'react', 'css', 'php'],
  },
  {
    id: 'moviefinder-app-rust',
    title: 'moviefinder.app (Rust)',
    setting: 'side',
    deployment: {
      t: 'public',
      url: 'https://moviefinder-app-rust.chrisvouga.dev',
    },
    code: {
      t: 'public',
      url: 'https://github.com/crvouga/moviefinder.app-rust',
    },
    description:
      'Rust implementation of the moviefinder.app movie discovery platform.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/moviefinder-app-rust-screenshot.optimized.webp'],
    galleryImageSrc: ['/moviefinder-app-rust-screenshot.png'],
    topics: ['rust'],
  },
  {
    id: 'headless-combobox-svelte-example',
    title: 'headless-combobox',
    setting: 'side',
    deployment: {
      t: 'public',
      url: 'https://svelte-headlesscombobox.chrisvouga.dev',
    },
    code: { t: 'public', url: 'https://github.com/crvouga/headless-combobox' },
    description:
      "A production-ready, headless TypeScript combobox library that's framework-agnostic, zero-dependency, and fully accessible. Enables developers to build custom combobox components in any UI framework while maintaining WCAG compliance and flexibility.",
    imageAlt: IMAGE_ALT,
    imageSrc: ['./headless-combobox-screenshot.optimized.webp'],
    galleryImageSrc: ['./headless-combobox-screenshot.png'],
    topics: ['typescript'],
  },
  {
    id: 'headless-combobox-docs',
    title: 'headless-combobox docs',
    setting: 'side',
    deployment: { t: 'public', url: 'https://headlesscombobox.chrisvouga.dev' },
    code: { t: 'public', url: 'https://github.com/crvouga/headless-combobox' },
    description: 'Documentation site for the headless-combobox library.',
    imageAlt: IMAGE_ALT,
    imageSrc: [],
    galleryImageSrc: [],
    topics: ['typescript'],
  },
  {
    id: 'todo-app',
    title: 'Fullstack Todo App',
    setting: 'side',
    deployment: { t: 'public', url: 'https://todo.chrisvouga.dev' },
    code: { t: 'public', url: 'https://github.com/crvouga/todo-v1' },
    description:
      'Full-stack task management application with user authentication and real-time synchronization. Demonstrates end-to-end development capabilities from database design to responsive UI implementation.',
    imageAlt: IMAGE_ALT,
    imageSrc: [
      '/fullstack-todo-app-screenshot.optimized.webp',
      '/todo.optimized.webp',
    ],
    galleryImageSrc: ['/fullstack-todo-app-screenshot.png', '/todo.png'],
    topics: [
      'typescript',
      'vue',
      'css',
      'express',
      'javascript',
      'tailwind',
      'nodejs',
      'mongodb',
    ],
  },
  {
    id: 'image-service',
    title: 'Image service',
    setting: 'side',
    deployment: { t: 'public', url: 'https://imageservice.chrisvouga.dev' },
    code: {
      t: 'public',
      url: 'https://github.com/crvouga/imageresizerservice.com',
    },
    description:
      'Image optimization service built with Go, designed for zero-configuration self-hosting and long-term maintainability. Enables web applications to efficiently serve optimized images without external dependencies.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/image-service-screenshot.optimized.webp'],
    galleryImageSrc: ['/image-service-screenshot.png'],
    topics: ['go'],
  },
  {
    id: 'llm-proxy',
    title: 'LLM Proxy',
    setting: 'side',
    deployment: { t: 'public', url: 'https://llm-proxy.chrisvouga.dev' },
    code: { t: 'public', url: 'https://github.com/crvouga/llm-server' },
    description:
      'Self-hosted OpenAI-compatible HTTP proxy that routes requests to configurable upstream APIs, supports custom auth headers (API keys and bearer tokens), and logs traffic to Postgres for analysis, health checks, and cost visibility.',
    imageAlt: IMAGE_ALT,
    imageSrc: ['/llm-proxy-screenshot.optimized.webp'],
    galleryImageSrc: [
      '/llm-proxy-screenshot.png',
      toYouTubeVideoUrl({
        youTubeVideoId: 'Zsrk8x2X2uc',
        autoplay: true,
        mute: true,
      }),
    ],
    topics: [
      'typescript',
      'react',
      'tailwind',
      'bun',
      'postgres',
      'docker',
      'nodejs',
    ],
    resume: { priority: 90 },
  },
  {
    id: 'connect-four',
    title: 'Connect Four: AI & Multiplayer',
    setting: 'side',
    deployment: { t: 'public', url: 'https://connectfour.chrisvouga.dev/' },
    code: { t: 'public', url: 'https://github.com/crvouga/connect-four' },
    description:
      'Real-time multiplayer Connect Four game with WebSocket-based synchronization. Features smooth animations, responsive design, and seamless online gameplay for multiple concurrent users.',
    imageAlt: IMAGE_ALT,
    imageSrc: [
      '/connect-four-ai-multiplayer-screenshot.optimized.webp',
      '/connect-four.optimized.webp',
    ],
    galleryImageSrc: [
      '/connect-four-ai-multiplayer-screenshot.png',
      toYouTubeVideoUrl({
        youTubeVideoId: '9_TbyftkaQw',
        autoplay: true,
        mute: true,
      }),
      '/connect-four.png',
    ],
    topics: [
      'css',
      'greensock',
      'heroku',
      'material-ui',
      'nodejs',
      'ramda',
      'redux',
      'redux-saga',
      'javascript',
      'socket-io',
    ],
  },
];
