//
//
//
// Topics
// source: https://svglogos.dev/
//
//
//

export const TOPIC_TO_IMAGE_SRC = {
  // neo4j: "/neo4j.svg",
  neo4j: null,
  graphene: "/graphene.svg",
  flask: "/flask-light.svg",
  salesforce: "/salesforce.svg",
  dynamodb: "/aws-dynamodb.svg",
  php: "/php.svg",
  drupal: "/drupal-icon.svg",
  typescript: "/typescript-icon.svg",
  heroku: "/heroku-icon.svg",
  jest: "/jest.svg",
  "redux-saga": "/redux-saga.svg",
  ramda: "/ramda-light.svg",
  react: "/react.svg",
  firebase: "/firebase.svg",
  docker: "/docker-icon.svg",
  supabase: "/supabase-icon.svg",
  postgres: "/postgresql.svg",
  "material-ui": "/material-ui.svg",
  nextjs: "/nextjs-light.svg",
  "socket-io": "/socket.io.svg",
  // express: "/express-light.svg",
  express: null,
  css: "/css-3.svg",
  shopify: "/shopify.svg",
  sanity: "/sanity.svg",
  nodejs: "/nodejs-icon.svg",
  puppeteer: "/puppeteer.svg",
  redux: "/redux.svg",
  rxjs: "/rxjs.svg",
  elm: "/elm.svg",
  "react-query": "react-query-icon.svg",
  greensock: "/greensock-icon.svg",
  javascript: "/javascript.svg",
  vue: "/vue.svg",
  tailwind: "/tailwindcss.svg",
  mongodb: "/mongodb-icon.svg",
  bootstrap: "/bootstrap.svg",
  graphql: "/graphql.svg",
  gridsome: "/gridsome-icon.svg",
  mysql: "/mysql.svg",
  nuxt: "/nuxt-icon.svg",
  python: "/python.svg",
  // aws: "/aws.svg",
  aws: null,
  bun: "/bun.svg",
  websocket: "/websocket-light.svg",
  alphinejs: "/alpinejs-icon.svg",
  roc: "/roc.svg",
  htmx: "/htmx.svg",
  sqlite: "/sqlite.svg",
  rust: "/rust-light.svg",
  datastar: "/datastar-logo.optimized.webp",
  go: "/go.svg",
  trpc: "/trpc.svg",
  vercel: "/vercel-icon-light.svg",
  html: "/html-5.svg",
  s3: "/aws-s3.svg",
  zod: "/zod.svg",
};

/**
 * @typedef {keyof typeof TOPIC_TO_IMAGE_SRC} Topic
 */

/**
 * @type {{ [key in Topic]: string; }}
 */
export const TOPIC_TO_NAME = {
  html: "HTML",
  neo4j: "Neo4j",
  flask: "Flask",
  graphene: "Graphene",
  salesforce: "Salesforce",
  dynamodb: "DynamoDB",
  drupal: "Drupal",
  php: "PHP",
  typescript: "TypeScript",
  heroku: "Heroku",
  jest: "Jest",
  "redux-saga": "Redux Saga",
  ramda: "Ramda",
  react: "React",
  firebase: "Firebase",
  docker: "Docker",
  supabase: "Supabase",
  postgres: "Postgres",
  "material-ui": "Material UI",
  nextjs: "Next.js",
  "socket-io": "Socket.io",
  express: "Express",
  css: "CSS",
  shopify: "Shopify",
  sanity: "Sanity",
  nodejs: "Node.js",
  puppeteer: "Puppeteer",
  redux: "Redux",
  rxjs: "RxJS",
  elm: "Elm",
  "react-query": "React Query",
  greensock: "Greensock",
  javascript: "JavaScript",
  vue: "Vue",
  tailwind: "Tailwind",
  mongodb: "MongoDB",
  bootstrap: "Bootstrap",
  graphql: "GraphQL",
  gridsome: "Gridsome",
  mysql: "MySQL",
  nuxt: "Nuxt",
  python: "Python",
  aws: "AWS",
  bun: "Bun",
  websocket: "Web Sockets",
  roc: "Roc",
  alphinejs: "Alphine.js",
  htmx: "htmx",
  sqlite: "SQLite",
  rust: "Rust",
  datastar: "Datastar",
  go: "Go",
  trpc: "TRPC",
  vercel: "Vercel",
  s3: "S3",
  zod: "Zod",
};
