import { assert, hotAssert, type Assert } from "@pkgs/assert";
import type { ServiceSpec } from "./schema.js";

const ha: Assert = hotAssert();

/** Path of the caller workflow every sibling repo commits. */
export const PUBLISH_WORKFLOW_PATH = ".github/workflows/publish.yml";

/** Pre-rename path `rollout-publish` deletes when it finds it. */
export const LEGACY_PUBLISH_WORKFLOW_PATH = ".github/workflows/publish-image.yml";

export type PublishWorkflowService = Pick<ServiceSpec, "id" | "dockerfile" | "build_context">;

export type PublishWorkflowOptions = {
  readonly infraRepo: string;
  readonly imagePrefix: string;
  readonly imageOwner: string;
};

export function publishJobName(service: PublishWorkflowService): string {
  assert.nonEmptyString(service.id, "publish service id must be non-empty");
  const name = service.id.replace(/[^a-zA-Z0-9]/g, "_");
  assert.nonEmptyString(name, "publish job name must be non-empty");
  return name;
}

/**
 * The sibling-repo publish workflow. Each job calls the monorepo's single
 * `.github/workflows/ci.yml` (workflow_call), which builds/pushes the image and
 * dispatches `deploy-service` back to infra. Shared by `rollout-publish` (which
 * pushes it) and `llms.txt` (which documents it), so the two cannot disagree.
 */
export function renderPublishWorkflow(
  services: readonly PublishWorkflowService[],
  options: PublishWorkflowOptions,
): string {
  assert.nonEmptyArray(services, "publish workflow needs at least one service");
  assert.nonEmptyString(options.infraRepo, "publish infra repo must be non-empty");
  assert.nonEmptyString(options.imagePrefix, "publish image prefix must be non-empty");
  assert.nonEmptyString(options.imageOwner, "publish image owner must be non-empty");
  const jobs = services
    .map((s) => {
      ha.nonEmptyString(s.dockerfile, "publish service dockerfile must be non-empty");
      ha.nonEmptyString(s.build_context, "publish service build context must be non-empty");
      return `  ${publishJobName(s)}:
    uses: ${options.infraRepo}/.github/workflows/ci.yml@main
    secrets:
      DEPLOY_DISPATCH_TOKEN: \${{ secrets.DEPLOY_DISPATCH_TOKEN }}
      CALLER_GITHUB_TOKEN: \${{ github.token }}
    with:
      service_id: ${s.id}
      dockerfile: ${s.dockerfile}
      context: ${s.build_context}
      image_owner: ${options.imageOwner}
      image_prefix: ${options.imagePrefix}
      infra_github_repo: ${options.infraRepo}`;
    })
    .join("\n\n");

  // id-token: the called ci.yml `publish` job requests it, and a reusable
  // workflow's jobs can never hold more permissions than the caller grants.
  const workflow = `# AUTO-GENERATED by infra/scripts/rollout-publish-workflows.ts — do not edit.
name: Publish image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
${jobs}
`;
  assert.ok(workflow.includes("jobs:"), "publish workflow must define jobs");
  return workflow;
}
