/**
 * Generate `cloudflare/wrangler.toml` and `cloudflare/src/index.ts` from `projects.ts`.
 *
 * Run: bun run scripts/generate-cloudflare.ts
 */
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { join } from "node:path";
import { getDeployableProjects } from "../projects.js";
import {
  getGithubRepoSecretNames,
  getSecretsStoreId,
  secretBindingName,
} from "./cloudflare-secret-names.js";
import {
  WORKER_NAME,
  LEGACY_MIGRATION_TAG,
  LEGACY_CONTAINER_CLASS_NAMES,
  PREFIXED_MIGRATION_TAG,
  containerClassName,
  doBindingName,
} from "./cloudflare-resource-names.js";

let SECRETS_STORE_ID: string;
try {
  SECRETS_STORE_ID = getSecretsStoreId();
} catch (err) {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
}

const ACCOUNT_ID = process.env["CLOUDFLARE_ACCOUNT_ID"]?.trim();
if (process.env["GITHUB_ACTIONS"] === "true" && !ACCOUNT_ID) {
  console.error(
    "CLOUDFLARE_ACCOUNT_ID is required in GitHub Actions (repo secret → generate-cloudflare step env).",
  );
  process.exit(1);
}

/** Matches deployment-pipeline.yml: ghcr.io/${{ github.repository }}:<project-id>-latest */
const GHCR_IMAGE_REPO = (
  process.env["GITHUB_REPOSITORY"] ?? "crvouga/chrisvouga.dev"
).toLowerCase();

const ROOT = execSync("git rev-parse --show-toplevel", { encoding: "utf-8" }).trim();
const CF_DIR = join(ROOT, "cloudflare");
const SRC_DIR = join(CF_DIR, "src");

mkdirSync(SRC_DIR, { recursive: true });

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Target = {
  readonly id: string;
  readonly githubRepo: string;
  readonly hostname: string;
  readonly port: number;
  readonly secrets: readonly string[];
};

// ---------------------------------------------------------------------------
// Build target list (portfolio + everything from projects.ts)
// ---------------------------------------------------------------------------

const PORTFOLIO: Target = {
  id: "portfolio",
  githubRepo: "crvouga/chrisvouga.dev",
  hostname: "www.chrisvouga.dev",
  port: 80,
  secrets: [],
};

const TARGETS: readonly Target[] = [
  PORTFOLIO,
  ...getDeployableProjects().map((p) => ({
    id: p.id,
    githubRepo: p.githubRepo,
    hostname: p.hostname,
    port: p.port,
    secrets: p.secrets ?? [],
  })),
];

// Containers that need more than the default `lite` instance
const BASIC_INSTANCE_IDS = new Set<string>([
  "pickflix",
  "todo-app",
  "normalizer-app",
  "moviefinder-app-rust",
  "moviefinder-app-go",
  "moviefinder-app-react",
  "moviefinder-app-clojurescript",
]);

function instanceType(id: string): "lite" | "basic" {
  return BASIC_INSTANCE_IDS.has(id) ? "basic" : "lite";
}

/** Non-secret env vars (not in GitHub); PORT/STAGE/NODE_ENV for container apps. */
function staticContainerEnv(id: string, port: number): Record<string, string> {
  if (id === "pickflix") {
    return { NODE_ENV: "production" };
  }
  if (id.startsWith("moviefinder-app-")) {
    const env: Record<string, string> = { PORT: String(port) };
    if (id !== "moviefinder-app-clojurescript") {
      env["STAGE"] = "production";
    }
    return env;
  }
  return {};
}

// ---------------------------------------------------------------------------
// wrangler.toml generation
// ---------------------------------------------------------------------------

function generateWranglerToml(): string {
  const lines: string[] = [];
  lines.push("# AUTO-GENERATED by scripts/generate-cloudflare.ts -- do not edit by hand.");
  lines.push("");
  lines.push(`name = "${WORKER_NAME}"`);
  if (ACCOUNT_ID) {
    lines.push(`account_id = "${ACCOUNT_ID}"`);
  }
  lines.push(`main = "src/index.ts"`);
  lines.push(`compatibility_date = "2026-05-19"`);
  lines.push(`# Secrets Store ID: ${SECRETS_STORE_ID} (from CLOUDFLARE_SECRETS_STORE_ID / secrets.CLOUDFLARE_SECRETS_STORE_ID)`);
  lines.push("");

  // Containers
  for (const t of TARGETS) {
    lines.push(`# ${t.id}`);
    lines.push(`[[containers]]`);
    lines.push(`class_name = "${containerClassName(t.id)}"`);
    lines.push(`image = "ghcr.io/${GHCR_IMAGE_REPO}:${t.id}-latest"`);
    lines.push(`instance_type = "${instanceType(t.id)}"`);
    lines.push(`max_instances = 3`);
    lines.push("");
  }

  // Durable Object bindings
  for (const t of TARGETS) {
    lines.push(`[[durable_objects.bindings]]`);
    lines.push(`name = "${doBindingName(t.id)}"`);
    lines.push(`class_name = "${containerClassName(t.id)}"`);
    lines.push("");
  }

  // Routes (custom domains)
  for (const t of TARGETS) {
    lines.push(`# ${t.id} -> ${t.hostname}`);
    lines.push(`[[routes]]`);
    lines.push(`pattern = "${t.hostname}"`);
    lines.push(`custom_domain = true`);
    lines.push("");
  }

  // Secrets Store bindings
  const secretTargets = TARGETS.filter((t) => t.secrets.length > 0);
  if (secretTargets.length > 0) {
    lines.push(`# Secrets Store (store_id = ${SECRETS_STORE_ID})`);
    for (const t of secretTargets) {
      for (const s of t.secrets) {
        const binding = secretBindingName(t.id, s);
        lines.push(`[[secrets_store_secrets]]`);
        lines.push(`binding = "${binding}"`);
        lines.push(`store_id = "${SECRETS_STORE_ID}"`);
        lines.push(`secret_name = "${binding}"`);
        lines.push("");
      }
    }
  }

  const legacyClasses = LEGACY_CONTAINER_CLASS_NAMES.map((c) => `"${c}"`).join(", ");
  lines.push(`[[migrations]]`);
  lines.push(`tag = "${LEGACY_MIGRATION_TAG}"`);
  lines.push(`new_sqlite_classes = [${legacyClasses}]`);
  lines.push("");
  const prefixedClasses = TARGETS.map((t) => `"${containerClassName(t.id)}"`).join(", ");
  lines.push(`[[migrations]]`);
  lines.push(`tag = "${PREFIXED_MIGRATION_TAG}"`);
  lines.push(`new_sqlite_classes = [${prefixedClasses}]`);
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// src/index.ts generation
// ---------------------------------------------------------------------------

function generateIndexTs(): string {
  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by scripts/generate-cloudflare.ts -- do not edit by hand.`);
  lines.push("");
  lines.push(`import { Container, getContainer } from "@cloudflare/containers";`);
  lines.push("");

  // Secret resolution helpers
  lines.push(`export const SECRETS_STORE_ID = ${JSON.stringify(SECRETS_STORE_ID)};`);
  lines.push("");
  lines.push(`export class MissingSecretsError extends Error {`);
  lines.push(`  constructor(`);
  lines.push(`    readonly projectId: string,`);
  lines.push(`    readonly missing: readonly string[],`);
  lines.push(`  ) {`);
  lines.push(
    `    super(`,
  );
  lines.push(
    `      \`FATAL: Missing Secrets Store secrets for project "\${projectId}" in store "\${SECRETS_STORE_ID}": \${missing.join(", ")}. \` +`,
  );
  lines.push(
    `        \`Add GitHub repo secret and redeploy (CI seeds Secrets Store from GitHub).\`,`,
  );
  lines.push(`    );`);
  lines.push(`    this.name = "MissingSecretsError";`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");

  const envTargets = TARGETS.filter(
    (t) => t.secrets.length > 0 || Object.keys(staticContainerEnv(t.id, t.port)).length > 0,
  );
  if (envTargets.length > 0) {
    const withStatic = envTargets.filter(
      (t) => Object.keys(staticContainerEnv(t.id, t.port)).length > 0,
    );
    if (withStatic.length > 0) {
      lines.push(`const STATIC_ENV_SPECS = {`);
      for (const t of withStatic) {
        lines.push(`  "${t.id}": ${JSON.stringify(staticContainerEnv(t.id, t.port))},`);
      }
      lines.push(`} as const;`);
      lines.push("");
    }

    lines.push(`const SECRET_SPECS = {`);
    for (const t of envTargets) {
      if (t.secrets.length === 0) continue;
      lines.push(`  "${t.id}": [`);
      for (const s of t.secrets) {
        const binding = secretBindingName(t.id, s);
        lines.push(`    { containerKey: ${JSON.stringify(s)}, binding: ${JSON.stringify(binding)} },`);
      }
      lines.push(`  ],`);
    }
    lines.push(`} as const;`);
    lines.push("");
    lines.push(`type EnvProjectId = keyof typeof SECRET_SPECS;`);
    lines.push("");
    lines.push(`async function resolveContainerEnvVars(`);
    lines.push(`  projectId: EnvProjectId,`);
    lines.push(`  env: Env,`);
    lines.push(`): Promise<Record<string, string>> {`);
    lines.push(`  const specs = SECRET_SPECS[projectId];`);
    lines.push(
      `  const envVars: Record<string, string> = { ...(STATIC_ENV_SPECS[projectId as keyof typeof STATIC_ENV_SPECS] ?? {}) };`,
    );
    lines.push(`  const missing: string[] = [];`);
    lines.push("");
    lines.push(`  for (const { containerKey, binding } of specs) {`);
    lines.push(`    const storeBinding = env[binding as keyof Env] as SecretsStoreSecret | undefined;`);
    lines.push(`    if (storeBinding == null) {`);
    lines.push(`      missing.push(\`\${binding} (binding not configured)\`);`);
    lines.push(`      continue;`);
    lines.push(`    }`);
    lines.push(`    let value: string;`);
    lines.push(`    try {`);
    lines.push(`      value = await storeBinding.get();`);
    lines.push(`    } catch (err) {`);
    lines.push(`      const detail = err instanceof Error ? err.message : String(err);`);
    lines.push(`      missing.push(\`\${binding} (get() failed: \${detail})\`);`);
    lines.push(`      continue;`);
    lines.push(`    }`);
    lines.push(`    if (value === "") {`);
    lines.push(`      missing.push(\`\${binding} (empty value in Secrets Store)\`);`);
    lines.push(`      continue;`);
    lines.push(`    }`);
    lines.push(`    envVars[containerKey] = value;`);
    lines.push(`  }`);
    lines.push("");
    lines.push(`  if (missing.length > 0) {`);
    lines.push(`    throw new MissingSecretsError(projectId, missing);`);
    lines.push(`  }`);
    lines.push(`  return envVars;`);
    lines.push(`}`);
    lines.push("");
    lines.push(`async function ensureContainerSecrets(`);
    lines.push(`  projectId: EnvProjectId,`);
    lines.push(`  container: Container<Env>,`);
    lines.push(`  env: Env,`);
    lines.push(`): Promise<void> {`);
    lines.push(`  container.envVars = await resolveContainerEnvVars(projectId, env);`);
    lines.push(`}`);
    lines.push("");
    lines.push(`function secretsErrorResponse(projectId: string, err: unknown): Response {`);
    lines.push(`  const message =`);
    lines.push(`    err instanceof MissingSecretsError`);
    lines.push(`      ? err.message`);
    lines.push(`      : \`FATAL: Failed to load Secrets Store secrets for \${projectId}: \${`);
    lines.push(`          err instanceof Error ? err.message : String(err)`);
    lines.push(`        }\`;`);
    lines.push(`  console.error(message, err);`);
    lines.push(`  return new Response(message, {`);
    lines.push(`    status: 503,`);
    lines.push(`    headers: { "Content-Type": "text/plain; charset=utf-8" },`);
    lines.push(`  });`);
    lines.push(`}`);
    lines.push("");
  }

  // Env interface
  lines.push(`export interface Env {`);
  for (const t of TARGETS) {
    const className = containerClassName(t.id);
    lines.push(`  readonly ${doBindingName(t.id)}: DurableObjectNamespace<${className}>;`);
  }
  for (const t of TARGETS) {
    for (const s of t.secrets) {
      lines.push(`  readonly ${secretBindingName(t.id, s)}: SecretsStoreSecret;`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // Container classes
  for (const t of TARGETS) {
    const className = containerClassName(t.id);
    const hasSecrets =
      t.secrets.length > 0 || Object.keys(staticContainerEnv(t.id, t.port)).length > 0;
    lines.push(`export class ${className} extends Container<Env> {`);
    lines.push(`  defaultPort = ${t.port};`);
    lines.push(`  sleepAfter = "5m";`);
    if (hasSecrets) {
      lines.push(`  private secretsLoad?: Promise<void>;`);
      lines.push("");
      lines.push(`  async fetch(request: Request): Promise<Response> {`);
      lines.push(`    try {`);
      lines.push(`      this.secretsLoad ??= ensureContainerSecrets(${JSON.stringify(t.id)}, this, this.env);`);
      lines.push(`      await this.secretsLoad;`);
      lines.push(`    } catch (err) {`);
      lines.push(`      return secretsErrorResponse(${JSON.stringify(t.id)}, err);`);
      lines.push(`    }`);
      lines.push(`    return super.fetch(request);`);
      lines.push(`  }`);
    }
    lines.push(`}`);
    lines.push("");
  }

  // Hostname -> binding map
  lines.push(`const HOSTNAME_TO_BINDING: Record<string, keyof Env> = {`);
  for (const t of TARGETS) {
    lines.push(`  "${t.hostname}": "${doBindingName(t.id)}",`);
  }
  lines.push(`};`);
  lines.push("");
  lines.push(`type ContainerBindingKey = (typeof HOSTNAME_TO_BINDING)[keyof typeof HOSTNAME_TO_BINDING];`);
  lines.push("");

  // Worker fetch handler
  lines.push(`export default {`);
  lines.push(`  async fetch(request: Request, env: Env): Promise<Response> {`);
  lines.push(`    const url = new URL(request.url);`);
  lines.push(`    const hostname = url.hostname.toLowerCase();`);
  lines.push(`    const bindingKey = HOSTNAME_TO_BINDING[hostname];`);
  lines.push("");
  lines.push(`    if (!bindingKey) {`);
  lines.push(`      return new Response(`);
  lines.push(`        \`No container configured for hostname: \${hostname}\`,`);
  lines.push(`        { status: 404 },`);
  lines.push(`      );`);
  lines.push(`    }`);
  lines.push("");
  lines.push(`    const ns = env[bindingKey as ContainerBindingKey];`);
  lines.push(
    `    const instance = getContainer(ns as DurableObjectNamespace<Container<Env>>, hostname);`,
  );
  lines.push(`    return instance.fetch(request);`);
  lines.push(`  },`);
  lines.push(`} satisfies ExportedHandler<Env>;`);
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// deployment-pipeline.yml — GitHub secrets env block (source of truth)
// ---------------------------------------------------------------------------

const WORKFLOW_PATH = join(ROOT, ".github/workflows/deployment-pipeline.yml");
const WORKFLOW_SECRETS_BEGIN = "          # BEGIN GENERATED: cloudflare-github-secrets-env";
const WORKFLOW_SECRETS_END = "          # END GENERATED: cloudflare-github-secrets-env";

function generateWorkflowSecretsEnvBlock(): string {
  const lines = [WORKFLOW_SECRETS_BEGIN];
  for (const name of getGithubRepoSecretNames()) {
    lines.push(`          ${name}: \${{ secrets.${name} }}`);
  }
  lines.push(WORKFLOW_SECRETS_END);
  return lines.join("\n");
}

function syncWorkflowSecretsEnv(): void {
  const workflow = readFileSync(WORKFLOW_PATH, "utf-8");
  const pattern = new RegExp(
    `${WORKFLOW_SECRETS_BEGIN.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${WORKFLOW_SECRETS_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`,
  );
  if (!pattern.test(workflow)) {
    console.error(
      `Missing markers in ${WORKFLOW_PATH}. Add:\n${WORKFLOW_SECRETS_BEGIN}\n${WORKFLOW_SECRETS_END}`,
    );
    process.exit(1);
  }
  writeFileSync(WORKFLOW_PATH, workflow.replace(pattern, generateWorkflowSecretsEnvBlock()));
}

// ---------------------------------------------------------------------------
// Write files
// ---------------------------------------------------------------------------

writeFileSync(join(CF_DIR, "wrangler.toml"), generateWranglerToml());
writeFileSync(join(SRC_DIR, "index.ts"), generateIndexTs());
syncWorkflowSecretsEnv();

console.log(`Generated cloudflare/wrangler.toml`);
console.log(`Generated cloudflare/src/index.ts`);
console.log(`Synced GitHub secrets env in .github/workflows/deployment-pipeline.yml`);
console.log(`Secrets Store ID: ${SECRETS_STORE_ID}`);
console.log(`Targets: ${TARGETS.length}`);
for (const t of TARGETS) {
  const secretCount = t.secrets.length > 0 ? ` (${t.secrets.length} secrets)` : "";
  console.log(`  ${t.id.padEnd(40)} ${t.hostname.padEnd(50)} :${t.port}${secretCount}`);
}
