// AUTO-GENERATED by scripts/generate-cloudflare.ts -- do not edit by hand.

import { Container, getContainer } from "@cloudflare/containers";

export const SECRETS_STORE_ID = "chrisvouga";

export class MissingSecretsError extends Error {
  constructor(
    readonly projectId: string,
    readonly missing: readonly string[],
  ) {
    super(
      `FATAL: Missing Secrets Store secrets for project "${projectId}" in store "${SECRETS_STORE_ID}": ${missing.join(", ")}. ` +
        `Provision with: bun run setup-cloudflare-secrets (env vars must be set).`,
    );
    this.name = "MissingSecretsError";
  }
}

const SECRET_SPECS = {
  "pickflix": [
    { containerKey: "NODE_ENV", binding: "PICKFLIX__NODE_ENV" },
    { containerKey: "PORT", binding: "PICKFLIX__PORT" },
    { containerKey: "DATABASE_URL", binding: "PICKFLIX__DATABASE_URL" },
    { containerKey: "SECRET", binding: "PICKFLIX__SECRET" },
    { containerKey: "SEND_GRID_API_KEY", binding: "PICKFLIX__SEND_GRID_API_KEY" },
    { containerKey: "SEND_GRID_REGISTERED_EMAIL_ADDRESS", binding: "PICKFLIX__SEND_GRID_REGISTERED_EMAIL_ADDRESS" },
    { containerKey: "SESSION_COOKIE_SECRET", binding: "PICKFLIX__SESSION_COOKIE_SECRET" },
    { containerKey: "YOUTUBE_API_KEY", binding: "PICKFLIX__YOUTUBE_API_KEY" },
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "PICKFLIX__TMDB_API_READ_ACCESS_TOKEN" },
  ],
  "moviefinder-app-rust": [
    { containerKey: "STAGE", binding: "MOVIEFINDER_APP_RUST__STAGE" },
    { containerKey: "PORT", binding: "MOVIEFINDER_APP_RUST__PORT" },
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "MOVIEFINDER_APP_RUST__TMDB_API_READ_ACCESS_TOKEN" },
    { containerKey: "TWILIO_ACCOUNT_SID", binding: "MOVIEFINDER_APP_RUST__TWILIO_ACCOUNT_SID" },
    { containerKey: "TWILIO_AUTH_TOKEN", binding: "MOVIEFINDER_APP_RUST__TWILIO_AUTH_TOKEN" },
    { containerKey: "TWILIO_SERVICE_SID", binding: "MOVIEFINDER_APP_RUST__TWILIO_SERVICE_SID" },
  ],
  "moviefinder-app-go": [
    { containerKey: "STAGE", binding: "MOVIEFINDER_APP_GO__STAGE" },
    { containerKey: "PORT", binding: "MOVIEFINDER_APP_GO__PORT" },
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "MOVIEFINDER_APP_GO__TMDB_API_READ_ACCESS_TOKEN" },
    { containerKey: "TWILIO_ACCOUNT_SID", binding: "MOVIEFINDER_APP_GO__TWILIO_ACCOUNT_SID" },
    { containerKey: "TWILIO_AUTH_TOKEN", binding: "MOVIEFINDER_APP_GO__TWILIO_AUTH_TOKEN" },
    { containerKey: "TWILIO_SERVICE_SID", binding: "MOVIEFINDER_APP_GO__TWILIO_SERVICE_SID" },
  ],
  "moviefinder-app-react": [
    { containerKey: "STAGE", binding: "MOVIEFINDER_APP_REACT__STAGE" },
    { containerKey: "PORT", binding: "MOVIEFINDER_APP_REACT__PORT" },
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "MOVIEFINDER_APP_REACT__TMDB_API_READ_ACCESS_TOKEN" },
    { containerKey: "TWILIO_ACCOUNT_SID", binding: "MOVIEFINDER_APP_REACT__TWILIO_ACCOUNT_SID" },
    { containerKey: "TWILIO_AUTH_TOKEN", binding: "MOVIEFINDER_APP_REACT__TWILIO_AUTH_TOKEN" },
    { containerKey: "TWILIO_SERVICE_SID", binding: "MOVIEFINDER_APP_REACT__TWILIO_SERVICE_SID" },
  ],
  "moviefinder-app-clojurescript": [
    { containerKey: "PORT", binding: "MOVIEFINDER_APP_CLOJURESCRIPT__PORT" },
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "MOVIEFINDER_APP_CLOJURESCRIPT__TMDB_API_READ_ACCESS_TOKEN" },
    { containerKey: "TWILIO_ACCOUNT_SID", binding: "MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_ACCOUNT_SID" },
    { containerKey: "TWILIO_AUTH_TOKEN", binding: "MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_AUTH_TOKEN" },
    { containerKey: "TWILIO_SERVICE_SID", binding: "MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_SERVICE_SID" },
  ],
} as const;

type SecretProjectId = keyof typeof SECRET_SPECS;

async function resolveContainerEnvVars(
  projectId: SecretProjectId,
  env: Env,
): Promise<Record<string, string>> {
  const specs = SECRET_SPECS[projectId];
  const envVars: Record<string, string> = {};
  const missing: string[] = [];

  for (const { containerKey, binding } of specs) {
    const storeBinding = env[binding as keyof Env] as SecretsStoreSecret | undefined;
    if (storeBinding == null) {
      missing.push(`${binding} (binding not configured)`);
      continue;
    }
    let value: string;
    try {
      value = await storeBinding.get();
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      missing.push(`${binding} (get() failed: ${detail})`);
      continue;
    }
    if (value === "") {
      missing.push(`${binding} (empty value in Secrets Store)`);
      continue;
    }
    envVars[containerKey] = value;
  }

  if (missing.length > 0) {
    throw new MissingSecretsError(projectId, missing);
  }
  return envVars;
}

async function ensureContainerSecrets(
  projectId: SecretProjectId,
  container: Container<Env>,
  env: Env,
): Promise<void> {
  container.envVars = await resolveContainerEnvVars(projectId, env);
}

function secretsErrorResponse(projectId: string, err: unknown): Response {
  const message =
    err instanceof MissingSecretsError
      ? err.message
      : `FATAL: Failed to load Secrets Store secrets for ${projectId}: ${
          err instanceof Error ? err.message : String(err)
        }`;
  console.error(message, err);
  return new Response(message, {
    status: 503,
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}

export interface Env {
  readonly PORTFOLIO: DurableObjectNamespace<Portfolio>;
  readonly PICKFLIX: DurableObjectNamespace<Pickflix>;
  readonly HEADLESS_COMBOBOX_SVELTE_EXAMPLE: DurableObjectNamespace<HeadlessComboboxSvelteExample>;
  readonly HEADLESS_COMBOBOX_DOCS: DurableObjectNamespace<HeadlessComboboxDocs>;
  readonly TODO_APP: DurableObjectNamespace<TodoApp>;
  readonly IMAGE_SERVICE: DurableObjectNamespace<ImageService>;
  readonly CONNECT_FOUR: DurableObjectNamespace<ConnectFour>;
  readonly NORMALIZER_APP: DurableObjectNamespace<NormalizerApp>;
  readonly SCREENSHOT_SERVICE: DurableObjectNamespace<ScreenshotService>;
  readonly SMART_DOG_DOOR: DurableObjectNamespace<SmartDogDoor>;
  readonly QUIZ_MAKER: DurableObjectNamespace<QuizMaker>;
  readonly ANIME_BLOG: DurableObjectNamespace<AnimeBlog>;
  readonly SNAKE_GAME: DurableObjectNamespace<SnakeGame>;
  readonly MATCH_THREE: DurableObjectNamespace<MatchThree>;
  readonly MOVIEFINDER_APP_RUST: DurableObjectNamespace<MoviefinderAppRust>;
  readonly MOVIEFINDER_APP_GO: DurableObjectNamespace<MoviefinderAppGo>;
  readonly MOVIEFINDER_APP_REACT: DurableObjectNamespace<MoviefinderAppReact>;
  readonly MOVIEFINDER_APP_CLOJURESCRIPT: DurableObjectNamespace<MoviefinderAppClojurescript>;
  readonly SIMON_SAYS: DurableObjectNamespace<SimonSays>;
  readonly CHEESE: DurableObjectNamespace<Cheese>;
  readonly PICKFLIX__NODE_ENV: SecretsStoreSecret;
  readonly PICKFLIX__PORT: SecretsStoreSecret;
  readonly PICKFLIX__DATABASE_URL: SecretsStoreSecret;
  readonly PICKFLIX__SECRET: SecretsStoreSecret;
  readonly PICKFLIX__SEND_GRID_API_KEY: SecretsStoreSecret;
  readonly PICKFLIX__SEND_GRID_REGISTERED_EMAIL_ADDRESS: SecretsStoreSecret;
  readonly PICKFLIX__SESSION_COOKIE_SECRET: SecretsStoreSecret;
  readonly PICKFLIX__YOUTUBE_API_KEY: SecretsStoreSecret;
  readonly PICKFLIX__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_RUST__STAGE: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_RUST__PORT: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_RUST__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_RUST__TWILIO_ACCOUNT_SID: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_RUST__TWILIO_AUTH_TOKEN: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_RUST__TWILIO_SERVICE_SID: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_GO__STAGE: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_GO__PORT: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_GO__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_GO__TWILIO_ACCOUNT_SID: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_GO__TWILIO_AUTH_TOKEN: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_GO__TWILIO_SERVICE_SID: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_REACT__STAGE: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_REACT__PORT: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_REACT__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_REACT__TWILIO_ACCOUNT_SID: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_REACT__TWILIO_AUTH_TOKEN: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_REACT__TWILIO_SERVICE_SID: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_CLOJURESCRIPT__PORT: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_CLOJURESCRIPT__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_ACCOUNT_SID: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_AUTH_TOKEN: SecretsStoreSecret;
  readonly MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_SERVICE_SID: SecretsStoreSecret;
}

export class Portfolio extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class Pickflix extends Container<Env> {
  defaultPort = 3000;
  sleepAfter = "5m";
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("pickflix", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("pickflix", err);
    }
    return super.fetch(request);
  }
}

export class HeadlessComboboxSvelteExample extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class HeadlessComboboxDocs extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class TodoApp extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class ImageService extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class ConnectFour extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class NormalizerApp extends Container<Env> {
  defaultPort = 8080;
  sleepAfter = "5m";
}

export class ScreenshotService extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class SmartDogDoor extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class QuizMaker extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class AnimeBlog extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class SnakeGame extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class MatchThree extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class MoviefinderAppRust extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("moviefinder-app-rust", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("moviefinder-app-rust", err);
    }
    return super.fetch(request);
  }
}

export class MoviefinderAppGo extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("moviefinder-app-go", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("moviefinder-app-go", err);
    }
    return super.fetch(request);
  }
}

export class MoviefinderAppReact extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("moviefinder-app-react", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("moviefinder-app-react", err);
    }
    return super.fetch(request);
  }
}

export class MoviefinderAppClojurescript extends Container<Env> {
  defaultPort = 8888;
  sleepAfter = "5m";
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("moviefinder-app-clojurescript", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("moviefinder-app-clojurescript", err);
    }
    return super.fetch(request);
  }
}

export class SimonSays extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

export class Cheese extends Container<Env> {
  defaultPort = 80;
  sleepAfter = "5m";
}

const HOSTNAME_TO_BINDING: Record<string, keyof Env> = {
  "www.chrisvouga.dev": "PORTFOLIO",
  "pickflix.chrisvouga.dev": "PICKFLIX",
  "svelte.headlesscombobox.chrisvouga.dev": "HEADLESS_COMBOBOX_SVELTE_EXAMPLE",
  "headlesscombobox.chrisvouga.dev": "HEADLESS_COMBOBOX_DOCS",
  "todo.chrisvouga.dev": "TODO_APP",
  "imageservice.chrisvouga.dev": "IMAGE_SERVICE",
  "connectfour.chrisvouga.dev": "CONNECT_FOUR",
  "normalizer.app": "NORMALIZER_APP",
  "screenshotservice.chrisvouga.dev": "SCREENSHOT_SERVICE",
  "smartdogdoor.chrisvouga.dev": "SMART_DOG_DOOR",
  "quizmaker.chrisvouga.dev": "QUIZ_MAKER",
  "anime.chrisvouga.dev": "ANIME_BLOG",
  "snake.chrisvouga.dev": "SNAKE_GAME",
  "matchthree.chrisvouga.dev": "MATCH_THREE",
  "moviefinder-app-rust.chrisvouga.dev": "MOVIEFINDER_APP_RUST",
  "moviefinder-app-go.chrisvouga.dev": "MOVIEFINDER_APP_GO",
  "moviefinder-app-react.chrisvouga.dev": "MOVIEFINDER_APP_REACT",
  "moviefinder-app-clojurescript.chrisvouga.dev": "MOVIEFINDER_APP_CLOJURESCRIPT",
  "simonsays.chrisvouga.dev": "SIMON_SAYS",
  "cheese.chrisvouga.dev": "CHEESE",
};

type ContainerBindingKey = (typeof HOSTNAME_TO_BINDING)[keyof typeof HOSTNAME_TO_BINDING];

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const hostname = url.hostname.toLowerCase();
    const bindingKey = HOSTNAME_TO_BINDING[hostname];

    if (!bindingKey) {
      return new Response(
        `No container configured for hostname: ${hostname}`,
        { status: 404 },
      );
    }

    const ns = env[bindingKey as ContainerBindingKey];
    const instance = getContainer(ns as DurableObjectNamespace<Container<Env>>, hostname);
    return instance.fetch(request);
  },
} satisfies ExportedHandler<Env>;
