// AUTO-GENERATED by scripts/generate-cloudflare.ts -- do not edit by hand.

import { Container, getContainer } from "@cloudflare/containers";

export const SECRETS_STORE_ID = "06a5a7ee662b4e41b778c4eeb447f030";

export class MissingSecretsError extends Error {
  constructor(
    readonly projectId: string,
    readonly missing: readonly string[],
  ) {
    super(
      `FATAL: Missing Secrets Store secrets for project "${projectId}" in store "${SECRETS_STORE_ID}": ${missing.join(", ")}. ` +
        `Add GitHub repo secret and redeploy (CI seeds Secrets Store from GitHub).`,
    );
    this.name = "MissingSecretsError";
  }
}

const STATIC_ENV_SPECS = {
  "pickflix": {"NODE_ENV":"production"},
  "moviefinder-app-rust": {"PORT":"80","STAGE":"production"},
  "moviefinder-app-go": {"PORT":"80","STAGE":"production"},
  "moviefinder-app-react": {"PORT":"80","STAGE":"production"},
  "moviefinder-app-clojurescript": {"PORT":"8888"},
} as const;

const SECRET_SPECS = {
  "pickflix": [
    { containerKey: "DATABASE_URL", binding: "PORTFOLIO_PICKFLIX__DATABASE_URL" },
    { containerKey: "PORT", binding: "PORTFOLIO_PICKFLIX__PORT" },
    { containerKey: "SECRET", binding: "PORTFOLIO_PICKFLIX__SECRET" },
    { containerKey: "SEND_GRID_API_KEY", binding: "PORTFOLIO_PICKFLIX__SEND_GRID_API_KEY" },
    { containerKey: "SEND_GRID_REGISTERED_EMAIL_ADDRESS", binding: "PORTFOLIO_PICKFLIX__SEND_GRID_REGISTERED_EMAIL_ADDRESS" },
    { containerKey: "SESSION_COOKIE_SECRET", binding: "PORTFOLIO_PICKFLIX__SESSION_COOKIE_SECRET" },
    { containerKey: "YOUTUBE_API_KEY", binding: "PORTFOLIO_PICKFLIX__YOUTUBE_API_KEY" },
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "PORTFOLIO_PICKFLIX__TMDB_API_READ_ACCESS_TOKEN" },
  ],
  "moviefinder-app-rust": [
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "PORTFOLIO_MOVIEFINDER_APP_RUST__TMDB_API_READ_ACCESS_TOKEN" },
    { containerKey: "TWILIO_ACCOUNT_SID", binding: "PORTFOLIO_MOVIEFINDER_APP_RUST__TWILIO_ACCOUNT_SID" },
    { containerKey: "TWILIO_AUTH_TOKEN", binding: "PORTFOLIO_MOVIEFINDER_APP_RUST__TWILIO_AUTH_TOKEN" },
    { containerKey: "TWILIO_SERVICE_SID", binding: "PORTFOLIO_MOVIEFINDER_APP_RUST__TWILIO_SERVICE_SID" },
  ],
  "moviefinder-app-go": [
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "PORTFOLIO_MOVIEFINDER_APP_GO__TMDB_API_READ_ACCESS_TOKEN" },
    { containerKey: "TWILIO_ACCOUNT_SID", binding: "PORTFOLIO_MOVIEFINDER_APP_GO__TWILIO_ACCOUNT_SID" },
    { containerKey: "TWILIO_AUTH_TOKEN", binding: "PORTFOLIO_MOVIEFINDER_APP_GO__TWILIO_AUTH_TOKEN" },
    { containerKey: "TWILIO_SERVICE_SID", binding: "PORTFOLIO_MOVIEFINDER_APP_GO__TWILIO_SERVICE_SID" },
  ],
  "moviefinder-app-react": [
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "PORTFOLIO_MOVIEFINDER_APP_REACT__TMDB_API_READ_ACCESS_TOKEN" },
    { containerKey: "TWILIO_ACCOUNT_SID", binding: "PORTFOLIO_MOVIEFINDER_APP_REACT__TWILIO_ACCOUNT_SID" },
    { containerKey: "TWILIO_AUTH_TOKEN", binding: "PORTFOLIO_MOVIEFINDER_APP_REACT__TWILIO_AUTH_TOKEN" },
    { containerKey: "TWILIO_SERVICE_SID", binding: "PORTFOLIO_MOVIEFINDER_APP_REACT__TWILIO_SERVICE_SID" },
  ],
  "moviefinder-app-clojurescript": [
    { containerKey: "TMDB_API_READ_ACCESS_TOKEN", binding: "PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT__TMDB_API_READ_ACCESS_TOKEN" },
    { containerKey: "TWILIO_ACCOUNT_SID", binding: "PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_ACCOUNT_SID" },
    { containerKey: "TWILIO_AUTH_TOKEN", binding: "PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_AUTH_TOKEN" },
    { containerKey: "TWILIO_SERVICE_SID", binding: "PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_SERVICE_SID" },
  ],
} as const;

type EnvProjectId = keyof typeof SECRET_SPECS;

async function resolveContainerEnvVars(
  projectId: EnvProjectId,
  env: Env,
): Promise<Record<string, string>> {
  const specs = SECRET_SPECS[projectId];
  const envVars: Record<string, string> = { ...(STATIC_ENV_SPECS[projectId as keyof typeof STATIC_ENV_SPECS] ?? {}) };
  const missing: string[] = [];

  for (const { containerKey, binding } of specs) {
    const storeBinding = env[binding as keyof Env] as SecretsStoreSecret | undefined;
    if (storeBinding == null) {
      missing.push(`${binding} (binding not configured)`);
      continue;
    }
    let value: string;
    try {
      value = await storeBinding.get();
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      missing.push(`${binding} (get() failed: ${detail})`);
      continue;
    }
    if (value === "") {
      missing.push(`${binding} (empty value in Secrets Store)`);
      continue;
    }
    envVars[containerKey] = value;
  }

  if (missing.length > 0) {
    throw new MissingSecretsError(projectId, missing);
  }
  return envVars;
}

async function ensureContainerSecrets(
  projectId: EnvProjectId,
  container: Container<Env>,
  env: Env,
): Promise<void> {
  container.envVars = await resolveContainerEnvVars(projectId, env);
}

function secretsErrorResponse(projectId: string, err: unknown): Response {
  const message =
    err instanceof MissingSecretsError
      ? err.message
      : `FATAL: Failed to load Secrets Store secrets for ${projectId}: ${
          err instanceof Error ? err.message : String(err)
        }`;
  console.error(message, err);
  return new Response(message, {
    status: 503,
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}

export interface Env {
  readonly PORTFOLIO_PORTFOLIO: DurableObjectNamespace<Portfolio_Portfolio>;
  readonly PORTFOLIO_PICKFLIX: DurableObjectNamespace<Portfolio_Pickflix>;
  readonly PORTFOLIO_HEADLESS_COMBOBOX_SVELTE_EXAMPLE: DurableObjectNamespace<Portfolio_HeadlessComboboxSvelteExample>;
  readonly PORTFOLIO_HEADLESS_COMBOBOX_DOCS: DurableObjectNamespace<Portfolio_HeadlessComboboxDocs>;
  readonly PORTFOLIO_TODO_APP: DurableObjectNamespace<Portfolio_TodoApp>;
  readonly PORTFOLIO_IMAGE_SERVICE: DurableObjectNamespace<Portfolio_ImageService>;
  readonly PORTFOLIO_CONNECT_FOUR: DurableObjectNamespace<Portfolio_ConnectFour>;
  readonly PORTFOLIO_NORMALIZER_APP: DurableObjectNamespace<Portfolio_NormalizerApp>;
  readonly PORTFOLIO_SCREENSHOT_SERVICE: DurableObjectNamespace<Portfolio_ScreenshotService>;
  readonly PORTFOLIO_SMART_DOG_DOOR: DurableObjectNamespace<Portfolio_SmartDogDoor>;
  readonly PORTFOLIO_QUIZ_MAKER: DurableObjectNamespace<Portfolio_QuizMaker>;
  readonly PORTFOLIO_ANIME_BLOG: DurableObjectNamespace<Portfolio_AnimeBlog>;
  readonly PORTFOLIO_SNAKE_GAME: DurableObjectNamespace<Portfolio_SnakeGame>;
  readonly PORTFOLIO_MATCH_THREE: DurableObjectNamespace<Portfolio_MatchThree>;
  readonly PORTFOLIO_MOVIEFINDER_APP_RUST: DurableObjectNamespace<Portfolio_MoviefinderAppRust>;
  readonly PORTFOLIO_MOVIEFINDER_APP_GO: DurableObjectNamespace<Portfolio_MoviefinderAppGo>;
  readonly PORTFOLIO_MOVIEFINDER_APP_REACT: DurableObjectNamespace<Portfolio_MoviefinderAppReact>;
  readonly PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT: DurableObjectNamespace<Portfolio_MoviefinderAppClojurescript>;
  readonly PORTFOLIO_SIMON_SAYS: DurableObjectNamespace<Portfolio_SimonSays>;
  readonly PORTFOLIO_PICKFLIX__DATABASE_URL: SecretsStoreSecret;
  readonly PORTFOLIO_PICKFLIX__PORT: SecretsStoreSecret;
  readonly PORTFOLIO_PICKFLIX__SECRET: SecretsStoreSecret;
  readonly PORTFOLIO_PICKFLIX__SEND_GRID_API_KEY: SecretsStoreSecret;
  readonly PORTFOLIO_PICKFLIX__SEND_GRID_REGISTERED_EMAIL_ADDRESS: SecretsStoreSecret;
  readonly PORTFOLIO_PICKFLIX__SESSION_COOKIE_SECRET: SecretsStoreSecret;
  readonly PORTFOLIO_PICKFLIX__YOUTUBE_API_KEY: SecretsStoreSecret;
  readonly PORTFOLIO_PICKFLIX__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_RUST__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_RUST__TWILIO_ACCOUNT_SID: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_RUST__TWILIO_AUTH_TOKEN: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_RUST__TWILIO_SERVICE_SID: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_GO__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_GO__TWILIO_ACCOUNT_SID: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_GO__TWILIO_AUTH_TOKEN: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_GO__TWILIO_SERVICE_SID: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_REACT__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_REACT__TWILIO_ACCOUNT_SID: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_REACT__TWILIO_AUTH_TOKEN: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_REACT__TWILIO_SERVICE_SID: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT__TMDB_API_READ_ACCESS_TOKEN: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_ACCOUNT_SID: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_AUTH_TOKEN: SecretsStoreSecret;
  readonly PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT__TWILIO_SERVICE_SID: SecretsStoreSecret;
}

export abstract class PortfolioContainerBase extends Container<Env> {
  sleepAfter = "5m";
  private startupPromise?: Promise<void>;

  protected async ensureStarted(): Promise<void> {
    if (!this.startupPromise) {
      const portToCheck = this.defaultPort ?? 80;
      this.startupPromise = this.start(undefined, {
        portToCheck,
        retries: 30,
        waitInterval: 500,
      }).finally(() => {
        this.startupPromise = undefined;
      });
    }

    await this.startupPromise;
  }

  override async fetch(request: Request): Promise<Response> {
    await this.ensureStarted();
    return super.fetch(request);
  }
}

export class Portfolio_Portfolio extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_Pickflix extends PortfolioContainerBase {
  defaultPort = 3000;
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("pickflix", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("pickflix", err);
    }
    return super.fetch(request);
  }
}

export class Portfolio_HeadlessComboboxSvelteExample extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_HeadlessComboboxDocs extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_TodoApp extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_ImageService extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_ConnectFour extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_NormalizerApp extends PortfolioContainerBase {
  defaultPort = 8080;
}

export class Portfolio_ScreenshotService extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_SmartDogDoor extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_QuizMaker extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_AnimeBlog extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_SnakeGame extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_MatchThree extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio_MoviefinderAppRust extends PortfolioContainerBase {
  defaultPort = 80;
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("moviefinder-app-rust", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("moviefinder-app-rust", err);
    }
    return super.fetch(request);
  }
}

export class Portfolio_MoviefinderAppGo extends PortfolioContainerBase {
  defaultPort = 80;
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("moviefinder-app-go", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("moviefinder-app-go", err);
    }
    return super.fetch(request);
  }
}

export class Portfolio_MoviefinderAppReact extends PortfolioContainerBase {
  defaultPort = 80;
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("moviefinder-app-react", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("moviefinder-app-react", err);
    }
    return super.fetch(request);
  }
}

export class Portfolio_MoviefinderAppClojurescript extends PortfolioContainerBase {
  defaultPort = 8888;
  private secretsLoad?: Promise<void>;

  async fetch(request: Request): Promise<Response> {
    try {
      this.secretsLoad ??= ensureContainerSecrets("moviefinder-app-clojurescript", this, this.env);
      await this.secretsLoad;
    } catch (err) {
      return secretsErrorResponse("moviefinder-app-clojurescript", err);
    }
    return super.fetch(request);
  }
}

export class Portfolio_SimonSays extends PortfolioContainerBase {
  defaultPort = 80;
}

export class Portfolio extends Portfolio_Portfolio {}

export class Pickflix extends Portfolio_Pickflix {}

export class HeadlessComboboxSvelteExample extends Portfolio_HeadlessComboboxSvelteExample {}

export class HeadlessComboboxDocs extends Portfolio_HeadlessComboboxDocs {}

export class TodoApp extends Portfolio_TodoApp {}

export class ImageService extends Portfolio_ImageService {}

export class ConnectFour extends Portfolio_ConnectFour {}

export class NormalizerApp extends Portfolio_NormalizerApp {}

export class ScreenshotService extends Portfolio_ScreenshotService {}

export class SmartDogDoor extends Portfolio_SmartDogDoor {}

export class QuizMaker extends Portfolio_QuizMaker {}

export class AnimeBlog extends Portfolio_AnimeBlog {}

export class SnakeGame extends Portfolio_SnakeGame {}

export class MatchThree extends Portfolio_MatchThree {}

export class MoviefinderAppRust extends Portfolio_MoviefinderAppRust {}

export class MoviefinderAppGo extends Portfolio_MoviefinderAppGo {}

export class MoviefinderAppReact extends Portfolio_MoviefinderAppReact {}

export class MoviefinderAppClojurescript extends Portfolio_MoviefinderAppClojurescript {}

export class SimonSays extends Portfolio_SimonSays {}

const HOSTNAME_TO_BINDING: Record<string, keyof Env> = {
  "www.chrisvouga.dev": "PORTFOLIO_PORTFOLIO",
  "pickflix.chrisvouga.dev": "PORTFOLIO_PICKFLIX",
  "svelte.headlesscombobox.chrisvouga.dev": "PORTFOLIO_HEADLESS_COMBOBOX_SVELTE_EXAMPLE",
  "headlesscombobox.chrisvouga.dev": "PORTFOLIO_HEADLESS_COMBOBOX_DOCS",
  "todo.chrisvouga.dev": "PORTFOLIO_TODO_APP",
  "imageservice.chrisvouga.dev": "PORTFOLIO_IMAGE_SERVICE",
  "connectfour.chrisvouga.dev": "PORTFOLIO_CONNECT_FOUR",
  "normalizer.chrisvouga.dev": "PORTFOLIO_NORMALIZER_APP",
  "screenshotservice.chrisvouga.dev": "PORTFOLIO_SCREENSHOT_SERVICE",
  "smartdogdoor.chrisvouga.dev": "PORTFOLIO_SMART_DOG_DOOR",
  "quizmaker.chrisvouga.dev": "PORTFOLIO_QUIZ_MAKER",
  "anime.chrisvouga.dev": "PORTFOLIO_ANIME_BLOG",
  "snake.chrisvouga.dev": "PORTFOLIO_SNAKE_GAME",
  "matchthree.chrisvouga.dev": "PORTFOLIO_MATCH_THREE",
  "moviefinder-app-rust.chrisvouga.dev": "PORTFOLIO_MOVIEFINDER_APP_RUST",
  "moviefinder-app-go.chrisvouga.dev": "PORTFOLIO_MOVIEFINDER_APP_GO",
  "moviefinder-app-react.chrisvouga.dev": "PORTFOLIO_MOVIEFINDER_APP_REACT",
  "moviefinder-app-clojurescript.chrisvouga.dev": "PORTFOLIO_MOVIEFINDER_APP_CLOJURESCRIPT",
  "simonsays.chrisvouga.dev": "PORTFOLIO_SIMON_SAYS",
};

type ContainerBindingKey = (typeof HOSTNAME_TO_BINDING)[keyof typeof HOSTNAME_TO_BINDING];

const RECOVERY_INSTANCE_SUFFIX = "recovery-v1";

function isRecoverableStartupFailure(bodyText: string): boolean {
  const normalized = bodyText.toLowerCase();
  return (
    normalized.includes("failed to start container") ||
    normalized.includes("the container is not running") ||
    normalized.includes("the operation was aborted") ||
    normalized.includes("there is no container instance available at this time")
  );
}

async function fetchContainerResponse(
  ns: DurableObjectNamespace<PortfolioContainerBase>,
  request: Request,
  instanceId: string,
): Promise<Response> {
  try {
    const instance = getContainer(ns, instanceId);
    return await instance.fetch(request);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return new Response(`Failed to start container: ${message}`, { status: 500 });
  }
}

async function fetchWithStartupRecovery(
  ns: DurableObjectNamespace<PortfolioContainerBase>,
  request: Request,
  hostname: string,
): Promise<Response> {
  const primaryResponse = await fetchContainerResponse(ns, request, hostname);
  if (!["GET", "HEAD", "OPTIONS"].includes(request.method.toUpperCase())) {
    return primaryResponse;
  }

  if (primaryResponse.status < 500) {
    return primaryResponse;
  }

  const primaryBody = await primaryResponse.clone().text();
  if (!isRecoverableStartupFailure(primaryBody)) {
    return primaryResponse;
  }

  const recoveryInstanceId = `${hostname}:${RECOVERY_INSTANCE_SUFFIX}`;
  const recoveryResponse = await fetchContainerResponse(ns, request, recoveryInstanceId);
  if (recoveryResponse.status < 500) {
    return recoveryResponse;
  }

  const recoveryBody = await recoveryResponse.clone().text();
  if (!isRecoverableStartupFailure(recoveryBody)) {
    return recoveryResponse;
  }

  return primaryResponse;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const hostname = url.hostname.toLowerCase();
    const bindingKey = HOSTNAME_TO_BINDING[hostname];

    if (!bindingKey) {
      return new Response(
        `No container configured for hostname: ${hostname}`,
        { status: 404 },
      );
    }

    const ns = env[bindingKey as ContainerBindingKey] as DurableObjectNamespace<PortfolioContainerBase>;
    return fetchWithStartupRecovery(ns, request, hostname);
  },
} satisfies ExportedHandler<Env>;
